// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password, is_chirpy_red)
    VALUES (gen_random_uuid (), NOW(), NOW(), $1, $2, FALSE)
RETURNING
    id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :many
TRUNCATE TABLE users CASCADE
`

type DeleteAllUsersRow struct {
}

func (q *Queries) DeleteAllUsers(ctx context.Context) ([]DeleteAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, deleteAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteAllUsersRow
	for rows.Next() {
		var i DeleteAllUsersRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    created_at,
    updated_at,
    email,
    hashed_password,
    is_chirpy_red
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const setIsChirpyRedWithId = `-- name: SetIsChirpyRedWithId :execrows
UPDATE
    users
SET
    is_chirpy_red = $2
WHERE
    id = $1
`

type SetIsChirpyRedWithIdParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

func (q *Queries) SetIsChirpyRedWithId(ctx context.Context, arg SetIsChirpyRedWithIdParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setIsChirpyRedWithId, arg.ID, arg.IsChirpyRed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserEmailAndPassword = `-- name: UpdateUserEmailAndPassword :one
UPDATE
    users
SET
    email = $2,
    hashed_password = $3,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id,
    updated_at,
    created_at,
    email,
    is_chirpy_red
`

type UpdateUserEmailAndPasswordParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

type UpdateUserEmailAndPasswordRow struct {
	ID          uuid.UUID
	UpdatedAt   time.Time
	CreatedAt   time.Time
	Email       string
	IsChirpyRed bool
}

func (q *Queries) UpdateUserEmailAndPassword(ctx context.Context, arg UpdateUserEmailAndPasswordParams) (UpdateUserEmailAndPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmailAndPassword, arg.ID, arg.Email, arg.HashedPassword)
	var i UpdateUserEmailAndPasswordRow
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Email,
		&i.IsChirpyRed,
	)
	return i, err
}
