# https://github.com/Huachao/vscode-restclient

@baseURL = http://localhost:8080

### Health Check Endpoint

GET {{baseURL}}/api/healthz

### Create a user

POST {{baseURL}}/api/users
Content-Type: application/json

{
  "email": "mloneusk@example.co"
}

### Create another user

POST {{baseURL}}/api/users
Content-Type: application/json

{
  "email": "dackjorsey@example.co"
}

### Create another user

POST {{baseURL}}/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com"
}

### Create a chirp

POST {{baseURL}}/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "e1dbb0e9-432e-449a-ac14-28478bb20065"
}

### Reset metrics and delete all users

POST {{baseURL}}/admin/reset